# Generated by Django 6.0.6 on 2026-06-16 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteStudentTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('gpa', models.FloatField(default=3.0)),
                ('stress_level', models.IntegerField(default=5)),
                ('study_hours', models.FloatField(default=4.0)),
                ('sleep_hours', models.FloatField(default=7.0)),
                ('mood', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('neutral', 'Neutral'), ('anxious', 'Anxious'), ('exhausted', 'Exhausted')], default='neutral', max_length=20)),
                ('missed_assignments', models.IntegerField(default=0)),
                ('pending_assignments', models.IntegerField(default=0)),
                ('completed_assignments', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PlannedStudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration_hours', models.FloatField(default=1.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='academictask',
            name='user',
        ),
        migrations.RemoveConstraint(
            model_name='dailytelemetrylog',
            name='unique_daily_telemetry_per_user_date',
        ),
        migrations.AddField(
            model_name='completestudenttelemetry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_streams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plannedstudysession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AcademicTask',
        ),
        migrations.AlterUniqueTogether(
            name='completestudenttelemetry',
            unique_together={('user', 'date')},
        ),
        migrations.DeleteModel(
            name='DailyTelemetryLog',
        ),
    ]
