# Generated by Django 6.0.6 on 2026-06-16 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_completestudenttelemetry_plannedstudysession_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plannedstudysession',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AddField(
            model_name='plannedstudysession',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plannedstudysession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_study_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
