# Generated by Django 6.0.6 on 2026-06-26 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_plannedstudysession_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CGPAPredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_gpa', models.FloatField(default=3.0)),
                ('credit_hours', models.FloatField(default=15.0)),
                ('assignment_completion', models.FloatField(default=0.0)),
                ('quiz_results', models.FloatField(default=0.0)),
                ('study_hours', models.FloatField(default=4.0)),
                ('focus_level', models.IntegerField(default=5)),
                ('predicted_gpa', models.FloatField(default=3.0)),
                ('subject_forecast', models.JSONField(blank=True, default=list)),
                ('semester_forecast', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cgpa_prediction_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SemesterSimulationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_hours', models.FloatField(default=4.0)),
                ('attendance', models.FloatField(default=75.0)),
                ('assignment_completion', models.FloatField(default=0.0)),
                ('quiz_performance', models.FloatField(default=0.0)),
                ('expected_gpa', models.FloatField(default=3.0)),
                ('expected_performance', models.CharField(default='Stable', max_length=40)),
                ('forecast_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_simulation_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
