# Generated by Django 6.0.6 on 2026-06-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engines', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedmaterial',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='generatedstudypack',
            old_name='generated_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='generatedstudypack',
            name='important_questions',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='uploadedmaterial',
            name='extracted_text',
            field=models.TextField(default='The datetime and django.utils.timezone modules are available, so you can do e.g. timezone.now'),
            preserve_default=False,
        ),
    ]
